# Generated by Django 4.1.1 on 2022-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostagemLigações',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=80)),
                ('conteudo', models.TextField()),
                ('tempoDeLigação', models.TimeField()),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
