# Generated by Django 4.1.1 on 2022-09-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemligações',
            name='tempoDeLigação',
            field=models.CharField(max_length=5),
        ),
    ]
